version: "3.8"

services:
  app:
    image: php:8.3-apache
    container_name: php_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    command: bash -c "a2enmod rewrite && sed -i 's|/var/www/html|/var/www/html/public|g' /etc/apache2/sites-available/000-default.conf && apache2-foreground"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: php_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
